#!/usr/bin/env python3
"""Back-fill reader-facing prose in the fragment files of a run.

Why this exists, and why it edits fragments rather than `graph.json`:

`graph.json` is a build artefact. It is regenerated by `merge_graph.py` from
`fragments/*.json` on every round, so cleaning the merged graph by hand is wiped
by the next merge — the run's own history shows the same IDs and the same merge
banners coming back after a fix. The fragments are the source of truth; clean
there and every downstream render is clean too, including ones produced by a
different session.

The cleaning itself is not a judgement call. Bookkeeping text (「本分片」「请主 Agent
裁决」「本条由主 Agent 从 N 条分片记录合并」, `[rom_A01 第7章]` tags, internal field
names) is mechanical, and `reader_prose.strip_process_text` already computes the
answer the renderers use. So this is a back-fill, not a rewrite: the same function
that hides the text at render time now removes it at source.

Two things it refuses to do silently:

* A record whose prose is *entirely* bookkeeping cleans to an empty string. That
  is often right — the renderer prints its own neutral line instead of a dangling
  fragment — but it is also how a real note could be erased by mistake, so such
  records are listed as `emptied` and are only cleared with `--allow-empty`.
* A field that shrinks past `--threshold` of its original length is flagged, for
  the same reason: a sentence carrying both content and bookkeeping can lose more
  than it should.

Usage:
    python backfill_reader_prose.py --run-dir runs/<book-range>            # 预演
    python backfill_reader_prose.py --run-dir runs/<book-range> --write    # 落盘
    python backfill_reader_prose.py --all --write                          # 全部 run
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from reader_prose import FALLBACK_ENUM_LABELS, strip_process_text  # noqa: E402

# Every field a reader can see. Kept in step with `reader_prose` / the renderers:
# adding a field here without adding it there means it gets cleaned at render time
# but never at source (or the reverse), which is exactly the drift this tool avoids.
PROSE_FIELDS = (
    "description", "reason", "observation", "interpretation", "summary",
    "resolution", "title", "label", "note", "notes", "detail", "conclusion",
)

# Arrays whose prose describes the story (as opposed to notes written for the
# analyst, such as `review_issues`, which are allowed to talk about chapters).
STORY_ARRAYS = (
    "entities", "events", "relations", "state_changes", "foreshadowing",
    "romance_routes", "intimate_acts", "level_conversions",
)


def load_enum_labels(run_dir: Path) -> dict[str, str]:
    path = run_dir / "display-vocabulary.json"
    if not path.is_file():
        return {}
    try:
        vocab = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    labels: dict[str, str] = {}
    for group in vocab.values():
        if not isinstance(group, dict):
            continue
        for key, value in group.items():
            if isinstance(value, str):
                labels.setdefault(key, value)
            elif isinstance(value, dict) and isinstance(value.get("label"), str):
                labels.setdefault(key, value["label"])
    return labels


def walk(node: object, path: str, out: list[tuple[str, str, str, str, object]]) -> None:
    """Yield (record_id, field, text, array_path, container) for every prose string."""
    if isinstance(node, dict):
        record_id = node.get("id")
        for key, value in node.items():
            if isinstance(value, str) and key in PROSE_FIELDS:
                out.append((str(record_id) if record_id else path, key, value, path, node))
            else:
                walk(value, f"{path}.{key}", out)
    elif isinstance(node, list):
        for index, item in enumerate(node):
            walk(item, f"{path}[{index}]", out)


def fragment_files(run_dir: Path) -> list[Path]:
    """Json files under fragments/ that actually hold graph data.

    The directory also holds working files with the same extension — extraction
    plans (`_plan-401-500.json`, `extraction-plan-101-500.json`, top-level lists of
    chapter ranges) and chapter-scoped side tables. They carry no `id`-keyed prose,
    and a plan is not a fragment, so they are skipped by name and by shape.
    """
    frag_dir = run_dir / "fragments"
    if not frag_dir.is_dir():
        return []
    files: list[Path] = []
    for path in sorted(frag_dir.glob("*.json")):
        if not path.is_file():
            continue
        if "plan" in path.name.lower():
            continue
        files.append(path)
    return files


def backfill_run(
    run_dir: Path,
    *,
    write: bool,
    allow_empty: bool,
    threshold: float,
    show: int,
) -> dict:
    labels = load_enum_labels(run_dir)
    files = fragment_files(run_dir)

    cleaned: list[dict] = []
    emptied: list[dict] = []
    shrunk: list[dict] = []
    per_file: dict[Path, int] = {}

    for path in files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"SKIP  {path.name}: 无法解析（{exc}）", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            # 计划文件、索引表之类的辅助文件不是分片，跳过而不是报错。
            print(f"SKIP  {path.name}: 顶层不是对象，按辅助文件跳过", file=sys.stderr)
            continue

        found: list[tuple[str, str, str, str, object]] = []
        for array_name in STORY_ARRAYS:
            walk(data.get(array_name) or [], array_name, found)

        changed_here = 0
        for record_id, field, text, array_path, container in found:
            after = strip_process_text(text, labels)
            if after == text:
                continue
            entry = {
                "file": path.name,
                "record": record_id,
                "array": array_path.split("[")[0],
                "field": field,
                "before": len(text),
                "after": len(after),
                # 原文与被删掉的部分都要留痕：预演时只看得到清洗结果的话，
                # 「整条变空」到底是找对了还是删过头，没人能判断。
                "text_before": text[:400],
                "text_after": after,
                "removed": (text[:400] if not after.strip() else ""),
            }
            if not after.strip():
                emptied.append(entry)
                if not allow_empty:
                    continue
            elif len(text) >= 60 and len(after) < len(text) * threshold:
                shrunk.append(entry)
            cleaned.append(entry)
            container[field] = after
            changed_here += 1

        if changed_here:
            per_file[path] = changed_here
            if write:
                path.write_text(
                    json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
                )

    if write and per_file:
        for path in per_file:
            backup = path.with_suffix(path.suffix + ".pre-backfill")
            if not backup.exists():
                shutil.copy(path, backup)

    return {
        "run": run_dir.name,
        "fragments": len(files),
        "files_touched": len(per_file),
        "cleaned": cleaned,
        "emptied": emptied,
        "shrunk": shrunk,
    }


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        description="Back-fill bookkeeping text out of reader-facing prose in the fragments.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--run-dir", type=Path, help="单个 run 目录")
    parser.add_argument("--all", action="store_true", help="处理 runs/ 下所有 run")
    parser.add_argument("--runs-root", type=Path, default=Path("runs"))
    parser.add_argument("--write", action="store_true", help="真正落盘（默认只预演）")
    parser.add_argument("--allow-empty", action="store_true",
                        help="允许把整条都是记账的记录清空（默认只报告不动）")
    parser.add_argument("--threshold", type=float, default=0.25,
                        help="清洗后不足原文这个比例就标记为疑似缩水（默认 0.25）")
    parser.add_argument("--show", type=int, default=4, help="每个 run 打印几条对照")
    parser.add_argument("--json", type=Path, help="把结果写成 JSON")
    args = parser.parse_args()

    if args.all:
        root = args.runs_root.resolve()
        runs = sorted(p for p in root.iterdir() if p.is_dir() and (p / "fragments").is_dir())
    elif args.run_dir:
        runs = [args.run_dir.resolve()]
    else:
        parser.error("需要 --run-dir 或 --all")

    reports = [
        backfill_run(
            run,
            write=args.write,
            allow_empty=args.allow_empty,
            threshold=args.threshold,
            show=args.show,
        )
        for run in runs
    ]

    total = 0
    total_empty = 0
    for report in reports:
        if report.get("skipped"):
            continue
        n, e, sh = len(report["cleaned"]), len(report["emptied"]), len(report["shrunk"])
        total += n
        total_empty += e
        mark = "★" if (e or sh) else " "
        mode = "已写入" if args.write else "预演"
        print(f"{mark} {report['run']:28s} 分片 {report['fragments']:3d} → 涉及 {report['files_touched']:2d} 个 "
              f"| 待清洗 {n:4d} 条 | 清空 {e:3d} | 疑似缩水 {sh:3d}   [{mode}]")
        for item in report["cleaned"][: args.show]:
            print(f"    [{item['array']}] {item['record']}.{item['field']}  {item['before']}→{item['after']} 字")
        if n > args.show:
            print(f"    … 另有 {n - args.show} 条")
        for item in report["emptied"][:2]:
            print(f"    ⚠ 清空需确认：{item['record']}.{item['field']}（{item['before']} 字全是记账）")

    print()
    print(f"合计待清洗 {total} 条；其中整条清空 {total_empty} 条"
          + ("" if args.allow_empty else "（已跳过，加 --allow-empty 才会清）"))
    if args.write:
        print("已备份为 *.pre-backfill；下一步重跑 merge_graph.py 让图谱生效，再跑 audit_reader_prose.py 确认归零。")
    else:
        print("这是预演。加 --write 才会落盘。")

    if args.json:
        args.json.resolve().write_text(
            json.dumps(reports, ensure_ascii=False, indent=2), encoding="utf-8"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
