#!/usr/bin/env python3
"""Build the canonical unified, chapter-synchronized dashboard.

The dashboard keeps one chapter snapshot as the source of truth while restoring the
reader-first light visual language of the original dashboard. Each panel chooses a
visual form that fits the information instead of flattening every domain into tables.
"""
from __future__ import annotations

import argparse
import html
import json
import shutil
from pathlib import Path
from typing import Any

from derive_novel_views import build_views
from filter_graph_asof import filter_graph
from io_utils import atomic_write_text


def build_model(
    graph: dict[str, Any],
    protagonists=(),
    gap_threshold: int = 3,
    collections: dict[str, Any] | None = None,
    cutoff: int | None = None,
) -> dict[str, Any]:
    scoped = filter_graph(graph, cutoff, strict=True) if cutoff is not None else graph
    meta = scoped.get("metadata") if isinstance(scoped.get("metadata"), dict) else {}
    return {
        "graph": scoped,
        "views": build_views(scoped, protagonists, max(1, gap_threshold)),
        "collections": collections or {"collections": []},
        "metadata": {
            "title": meta.get("title"),
            "chapter_start": meta.get("chapter_start"),
            "chapter_end": meta.get("chapter_end"),
            "cutoff": cutoff,
            "temporal_provenance_gaps": meta.get("temporal_provenance_gaps", []),
        },
    }


def build_html(model: dict[str, Any]) -> str:
    payload = json.dumps(model, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    title = html.escape(str(model.get("metadata", {}).get("title") or "Novel Knowledge Graph"))
    return TEMPLATE.replace("__PAYLOAD__", payload).replace("__TITLE__", title)


TEMPLATE = r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>__TITLE__ · 小说知识图谱</title>
<style>
:root{color-scheme:light;--bg:#f4f5f7;--surface:#fff;--surface2:#f8f9fb;--ink:#171a21;--muted:#687083;--line:#e2e5eb;--accent:#6157d8;--accent-soft:#eeecff;--good:#15845f;--warn:#b46a08;--danger:#b53c4b;--shadow:0 12px 40px rgba(26,30,44,.08);--b:var(--bg);--p:var(--surface);--l:var(--line);--t:var(--ink);--m:var(--muted);--a:var(--accent)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.55 Inter,"Segoe UI","Microsoft YaHei",sans-serif;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}button,input,select{font:inherit}button{cursor:pointer}
header{position:sticky;top:0;z-index:8;display:grid;grid-template-columns:minmax(260px,1fr) minmax(360px,620px);gap:24px;align-items:center;padding:14px 24px;background:rgba(255,255,255,.94);border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}.brand h1{font-size:19px;line-height:1.2;margin:0;font-weight:700}.brand p{margin:4px 0 0;color:var(--muted);font-size:12px}.chapter-control{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:center}.chapter-control b{color:var(--accent);white-space:nowrap}.chapter-control input{width:100%;accent-color:var(--accent)}.snapshot-state{color:var(--muted);font-size:12px;white-space:nowrap}
nav{position:sticky;top:76px;z-index:7;display:flex;gap:5px;overflow-x:auto;padding:8px 18px;background:rgba(255,255,255,.92);border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}nav button{border:0;background:transparent;color:var(--muted);border-radius:9px;padding:8px 12px;white-space:nowrap}nav button:hover{color:var(--accent);background:var(--surface2)}nav button.on{background:var(--accent-soft);color:var(--accent);font-weight:650}
main{max-width:1560px;margin:auto;padding:22px}.view-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;margin:0 0 18px}.view-head h2{font-size:22px;margin:0}.view-head p{margin:4px 0 0;color:var(--muted);font-size:12px}.eyebrow{font-size:11px;letter-spacing:.11em;text-transform:uppercase;color:var(--accent);font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:11px}.card{background:var(--surface);border:1px solid var(--line);border-radius:13px;padding:14px;box-shadow:0 3px 14px rgba(30,34,48,.03)}.card:hover{border-color:#cbc7f4}.metric-card{position:relative;overflow:hidden}.metric-card::after{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--accent)}.metric{font-size:26px;line-height:1;font-weight:750}.muted{color:var(--muted)}.tag{display:inline-flex;align-items:center;gap:5px;padding:3px 8px;border-radius:999px;background:var(--surface2);color:var(--muted);font-size:11px}.tag.accent{background:var(--accent-soft);color:var(--accent)}.tag.good{background:#eaf7f2;color:var(--good)}.tag.warn{background:#fff4e7;color:var(--warn)}.tag.danger{background:#fff0f2;color:var(--danger)}.chips{display:flex;gap:5px;flex-wrap:wrap}.empty{padding:42px;text-align:center;color:var(--muted);border:1px dashed #cfd3dc;border-radius:13px;background:rgba(255,255,255,.55)}
.scroll{overflow:auto;max-height:68vh;border:1px solid var(--line);border-radius:12px;background:var(--surface)}table{width:100%;border-collapse:collapse}th,td{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top;text-align:left;font-size:12px}th{position:sticky;top:0;background:var(--surface2);color:var(--muted);font-weight:650}tbody tr:hover{background:#fafaff}code{white-space:pre-wrap;font-size:11px;color:#454c5f}.warn{color:var(--warn)}
.hero{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(300px,.8fr);gap:14px;margin-bottom:14px}.hero-main{padding:20px;background:linear-gradient(135deg,#fff 0,#f8f7ff 100%);border:1px solid #dcd9f7;border-radius:16px}.hero-main h2{font-size:25px;margin:4px 0 8px}.hero-main p{margin:0;color:var(--muted);max-width:760px}.hero-side{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hero-side .card{display:flex;flex-direction:column;justify-content:center}
.graph-shell{position:relative;background:radial-gradient(circle at 50% 40%,#fff 0,#f7f8fb 58%,#eef1f5 100%);border:1px solid var(--line);border-radius:16px;overflow:hidden;box-shadow:var(--shadow)}.graph{height:68vh;min-height:520px}.graph-toolbar{position:absolute;left:14px;top:14px;z-index:4;display:flex;gap:6px;flex-wrap:wrap;max-width:calc(100% - 28px)}.graph-toolbar button,.ghost{border:1px solid var(--line);background:rgba(255,255,255,.94);color:var(--muted);border-radius:9px;padding:7px 10px;box-shadow:0 3px 12px rgba(30,34,48,.05)}.graph-toolbar button:hover,.ghost:hover{color:var(--accent);border-color:#bbb6f3}.graph-legend{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.legend-item{display:inline-flex;align-items:center;gap:5px;color:var(--muted);font-size:11px}.swatch{width:9px;height:9px;border-radius:50%}
.entity-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(235px,1fr));gap:11px}.entity-card{min-width:0;padding:15px;border:1px solid var(--line);border-radius:13px;background:var(--surface);cursor:pointer;text-align:left;transition:transform .14s,border-color .14s,box-shadow .14s}.entity-card:hover{transform:translateY(-1px);border-color:#bbb6f3;box-shadow:0 8px 24px rgba(41,37,92,.08)}.entity-card h3{font-size:15px;margin:7px 0 5px}.entity-card p{margin:0;color:var(--muted);font-size:12px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.entity-meta{display:flex;justify-content:space-between;gap:10px;margin-top:10px;color:var(--muted);font-size:11px}.entity-attrs{margin-top:10px;display:flex;gap:5px;flex-wrap:wrap}.searchbar{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:8px;margin:0 0 14px}.searchbar input{border:1px solid var(--line);border-radius:10px;background:var(--surface);padding:9px 11px;outline:none}.searchbar input:focus{border-color:#9a93ed;box-shadow:0 0 0 3px var(--accent-soft)}
.timeline{display:grid;gap:9px}.timeline-item{display:grid;grid-template-columns:74px 16px minmax(0,1fr);gap:10px;align-items:stretch}.timeline-chapter{color:var(--accent);font-weight:700;padding-top:10px}.timeline-rail{position:relative}.timeline-rail::before{content:'';position:absolute;left:7px;top:0;bottom:-9px;width:2px;background:#d9d6f4}.timeline-item:last-child .timeline-rail::before{bottom:50%}.timeline-dot{position:absolute;left:2px;top:15px;width:12px;height:12px;border-radius:50%;background:var(--accent);border:3px solid #fff;box-shadow:0 0 0 1px #bcb7ef}.timeline-body{padding:10px 12px;background:var(--surface);border:1px solid var(--line);border-radius:11px}.timeline-body h3{font-size:13px;margin:0 0 3px}.timeline-body p{font-size:12px;color:var(--muted);margin:0}
.arc-list{display:grid;gap:11px}.arc-card{background:var(--surface);border:1px solid var(--line);border-radius:13px;padding:14px}.arc-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.arc-head h3{font-size:14px;margin:0}.arc-range{color:var(--muted);font-size:11px}.arc-track{height:9px;border-radius:999px;background:#eceef3;position:relative;margin:12px 0 4px;overflow:hidden}.arc-bar{position:absolute;height:100%;border-radius:999px;background:linear-gradient(90deg,#8a82e6,#6157d8)}.arc-sub{color:var(--muted);font-size:11px}
.record-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:11px}.record-card{background:var(--surface);border:1px solid var(--line);border-radius:13px;padding:14px}.record-card h3{font-size:14px;margin:7px 0 5px}.record-card p{margin:0;color:var(--muted);font-size:12px}.record-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.record-value{font-size:20px;font-weight:750;color:var(--accent)}
.battle-card{border-left:3px solid #b9b4ec}.battle-card.victory{border-left-color:var(--good)}.battle-card.defeat{border-left-color:var(--danger)}.battle-card.draw{border-left-color:var(--warn)}
.foreshadow-card{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:12px;align-items:center}.foreshadow-node{padding:12px;border-radius:10px;background:var(--surface2)}.foreshadow-arrow{color:var(--accent);font-weight:800}.foreshadow-node b{display:block}.foreshadow-node span{font-size:11px;color:var(--muted)}
.level-group{background:var(--surface);border:1px solid var(--line);border-radius:13px;padding:14px}.level-group h3{margin:0 0 10px;font-size:14px}.level-ladder{display:flex;gap:7px;flex-wrap:wrap}.level-step{padding:6px 9px;border-radius:9px;background:var(--surface2);font-size:11px}.level-step.current{background:var(--accent-soft);color:var(--accent);font-weight:700}
.rhythm-chart{display:flex;align-items:flex-end;gap:3px;height:210px;padding:18px 8px 28px;border:1px solid var(--line);border-radius:13px;background:linear-gradient(#fff,#fafbfc);overflow-x:auto}.rhythm-bar{min-width:8px;border-radius:5px 5px 2px 2px;background:#b7b2ef;position:relative}.rhythm-bar:hover{background:var(--accent)}.rhythm-bar span{display:none;position:absolute;bottom:calc(100% + 6px);left:50%;transform:translateX(-50%);padding:4px 6px;border-radius:6px;background:#28253d;color:#fff;font-size:10px;white-space:nowrap;z-index:2}.rhythm-bar:hover span{display:block}
.romance-route{position:relative;padding-left:18px}.romance-route::before{content:'';position:absolute;left:0;top:4px;bottom:4px;width:3px;border-radius:4px;background:#d0517c}.intimacy-card{border-left:3px solid #d0517c}.consent-mutual{color:var(--good)}.consent-coerced,.consent-forced{color:var(--danger)}.consent-uncertain{color:var(--warn)}
.audit-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.audit-good{border-top:3px solid var(--good)}.audit-warn{border-top:3px solid var(--warn)}.audit-error{border-top:3px solid var(--danger)}
@media(max-width:900px){header{grid-template-columns:1fr;gap:10px}.chapter-control{grid-template-columns:auto 1fr}.snapshot-state{grid-column:1/-1}nav{top:124px}main{padding:14px}.hero{grid-template-columns:1fr}.graph{min-height:460px}.foreshadow-card{grid-template-columns:1fr}.foreshadow-arrow{transform:rotate(90deg);justify-self:center}}
</style>
<script src="cytoscape-3.34.3.min.js"></script>
</head>
<body>
<header>
  <div class="brand"><div class="eyebrow">Novel Knowledge Graph</div><h1>__TITLE__</h1><p>统一时序知识图谱 · 每个面板共享同一章节快照</p></div>
  <div class="chapter-control"><b>第 <span id="cl"></span> 章</b><input id="ch" type="range" step="1"><span id="state" class="snapshot-state"></span></div>
</header>
<nav id="tabs"></nav>
<main id="main"></main>
<script>
const B=__PAYLOAD__,G=B.graph||{},V=B.views||{},C=B.collections||{collections:[]},META=G.metadata||{};
const A=x=>Array.isArray(x)?x:[],N=x=>Number.isInteger(x)?x:null,E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const min=Number(B.metadata?.chapter_start??V.metadata?.chapter_start??0),max=Number(B.metadata?.chapter_end??V.metadata?.chapter_end??0),sl=document.getElementById('ch'),tabsEl=document.getElementById('tabs'),mainEl=document.getElementById('main');sl.min=min;sl.max=max;sl.value=max;let S=null,active='overview',cy=null,repoQuery='';
const TYPE_COLORS={character:'#675bd8',skill:'#25896a',martial_soul:'#d0517c',item:'#c17822',organization:'#4c77b7',location:'#3e8b9e',creature:'#79943e',title:'#9a5b37',concept:'#758097',level_axis:'#a8752b'};
const TYPE_LABELS={character:'人物',skill:'技能',martial_soul:'特殊能力',item:'物品',organization:'组织',location:'地点',creature:'生物',title:'称号',concept:'概念',level_axis:'等级体系'};
const REL_LABELS={parent_of:'亲子',teacher_of:'师生',student_of:'师徒',friend_of:'朋友',close_friend_of:'挚友',rival_of:'对手',enemy_of:'敌对',member_of:'隶属',affiliated_with:'归属',spouse_of:'夫妻',betrothed_to:'婚约',romantic_partner_of:'恋爱',love_interest_of:'感情',sibling_of:'手足',ally_of:'盟友',owns:'拥有',uses:'使用',located_in:'位于',owes_favor_to:'欠人情'};
const ACT_LABELS={witness_nudity:'目睹裸露',witness_intimacy:'目睹亲密',voyeurism:'窥视',exposure:'暴露',peeping_attempt:'窥视尝试',embrace:'拥抱',kiss:'亲吻',groping_breast:'触摸胸部',groping_buttock:'触摸臀部',groping_genital:'触摸私处',fondling:'爱抚',stripping:'脱衣',manual_stimulation:'手部刺激',oral_sex:'口交',intercourse:'性交',anal_intercourse:'肛交',masturbation:'自慰',ejaculation:'射精',sexual_harassment:'性骚扰',molestation:'猥亵',attempted_rape:'强奸未遂',rape:'强奸',sexual_proposition:'亲密提议',other_intimate:'其他亲密行为'};
function interval(r,c,a='valid_from',z='valid_to'){const s=N(r?.[a])??0,e=N(r?.[z]);return s<=c&&(e===null||c<=e)}
function nestedChapter(map,id,key){if(!map||typeof map!=='object')return null;const n=map[id];if(n&&typeof n==='object')return N(n[key]);return key==null?N(n):N(map[key])}
function histValue(rows,c,keys){const h=A(rows).filter(x=>(N(x.valid_from)??N(x.chapter)??1e15)<=c).sort((a,b)=>(N(a.valid_from)??N(a.chapter)??0)-(N(b.valid_from)??N(b.chapter)??0));if(!h.length)return undefined;const r=h.at(-1);for(const k of keys)if(Object.hasOwn(r,k))return structuredClone(r[k]);return undefined}
function nameAt(e,c){const h=histValue(e.name_history,c,['name','value']);if(typeof h==='string')return h;const first=N(e.name_first_chapter)??nestedChapter(META.name_first_chapter,e.id,null);if(first!==null)return first<=c?e.name:`[${e.type}:${e.id}]`;return c>=max?e.name:`[${e.type}:${e.id}]`}
function proseAt(e,field,c){const h=histValue(e[`${field}_history`],c,[field,'value','text']);if(h!==undefined)return h;const first=N(e[`${field}_chapter`])??N(e[`${field}_first_chapter`])??nestedChapter(META[`${field}_first_chapter`],e.id,null);if(first!==null)return first<=c?e[field]:undefined;return c>=max?e[field]:undefined}
function attrsAt(e,c){const out={};for(const r of [...A(e.attribute_history),...A(e.attributes_history)].sort((a,b)=>(N(a.chapter)??N(a.valid_from)??0)-(N(b.chapter)??N(b.valid_from)??0))){const at=N(r.chapter)??N(r.valid_from);if(at!==null&&at<=c){const k=r.key??r.attribute;if(typeof k==='string')out[k]=structuredClone(r.value)}}for(const [k,v] of Object.entries(e.attributes||{})){if(Object.hasOwn(out,k))continue;const first=nestedChapter(META.attribute_first_chapter,e.id,k);if((first!==null&&first<=c)||(first===null&&c>=max))out[k]=structuredClone(v)}return out}
function entityAt(e,c){const x={...e,name:nameAt(e,c),attributes:attrsAt(e,c)};const summary=proseAt(e,'summary',c),description=proseAt(e,'description',c);if(summary===undefined)delete x.summary;else x.summary=summary;if(description===undefined)delete x.description;else x.description=description;delete x.current_state;return x}
function safeName(id,names){return names[id]??id??''}function rewriteNames(text,names){let s=String(text??'');for(const e of A(G.entities)){if(typeof e.name==='string'&&e.name&&names[e.id]&&names[e.id]!==e.name)s=s.split(e.name).join(names[e.id])}return s}
function commitAt(x,c){x=structuredClone(x);x.observations=A(x.observations).filter(o=>(N(o.chapter)??0)<=c).sort((a,b)=>(N(a.chapter)??0)-(N(b.chapter)??0));if(N(x.resolved_chapter)!==null&&x.resolved_chapter>c){x.resolved_chapter=null;x.resolution=null}const s=[...x.observations].reverse().find(o=>typeof o.status==='string')?.status;if(s)x.status=s;else if(!x.resolved_chapter)x.status='active';return x}
function relationAt(x,c){x=structuredClone(x);const end=N(x.valid_to);x.observations=A(x.observations).filter(o=>(N(o.chapter)??0)<=c).sort((a,b)=>(N(a.chapter)??0)-(N(b.chapter)??0));if(end!==null&&end>c)delete x.valid_to;const s=[...x.observations].reverse().find(o=>typeof o.status==='string')?.status;if(s)x.status=s;else if(end!==null&&end>c&&!['active','uncertain',null].includes(x.status))x.status='active';return x}
function resourceAt(x,c,names){x=structuredClone(x);x.name=safeName(x.item_id,names)||x.name;x.role_history=A(x.role_history).filter(r=>(N(r.chapter)??0)<=c&&interval(r,c,'chapter','valid_to')).map(r=>({...r,entity:safeName(r.entity_id,names),location:safeName(r.location_id,names)}));x.quantity_history=A(x.quantity_history).filter(r=>(N(r.chapter)??0)<=c);x.current_quantities={};for(const r of x.quantity_history)if(r.entity_id)x.current_quantities[r.entity_id]=r.after;x.acquisition_count=x.role_history.filter(r=>r.action==='gained').length;return x}
function expr(q,s,stack=[]){const all=new Set(s.graph.entities.map(e=>e.id));if(!q||typeof q!=='object')return new Set();if(q.explicit_members)return new Set(A(q.explicit_members).filter(x=>all.has(x)));if(q.type)return new Set(s.graph.entities.filter(e=>e.type===q.type).map(e=>e.id));if(q.arc){const a=s.arcs.find(x=>x.id===q.arc);return new Set(A(a?.entity_ids).filter(x=>all.has(x)))}if(q.collection){if(stack.includes(q.collection))return new Set();const c=A(C.collections).find(x=>x.id===q.collection);return c?expr(c.expression,s,[...stack,q.collection]):new Set()}if(q.and){const ss=A(q.and).map(x=>expr(x,s,stack));return ss.length?new Set([...ss[0]].filter(x=>ss.slice(1).every(z=>z.has(x)))):new Set()}if(q.or){const o=new Set();for(const z of A(q.or).map(x=>expr(x,s,stack)))for(const x of z)o.add(x);return o}if(q.not){const bad=expr(q.not,s,stack);return new Set([...all].filter(x=>!bad.has(x)))}if(q.relation){const spec=typeof q.relation==='string'?{type:q.relation}:q.relation,o=new Set();for(const r of s.graph.relations){if((spec.type||spec.relation_type)&&r.relation_type!==(spec.type||spec.relation_type))continue;o.add(r.source_id);o.add(r.target_id)}return new Set([...o].filter(x=>all.has(x)))}return new Set()}
function snapshotAt(c){
 const entities=A(G.entities).filter(e=>(N(e.first_chapter)??0)<=c).map(e=>entityAt(e,c)),ids=new Set(entities.map(e=>e.id)),names=Object.fromEntries(entities.map(e=>[e.id,e.name]));
 const relations=A(G.relations).filter(r=>(N(r.valid_from)??0)<=c&&ids.has(r.source_id)&&ids.has(r.target_id)&&interval(r,c)).map(r=>relationAt(r,c)),relationById=Object.fromEntries(relations.map(r=>[r.id,r])),events=A(G.events).filter(e=>(N(e.chapter)??0)<=c),arcs=A(G.story_arcs).filter(a=>(N(a.chapter_start)??0)<=c).map(a=>N(a.chapter_end)!==null&&a.chapter_end>c?{...a,chapter_end:null,status:['closed','complete','completed','resolved'].includes(a.status)?'active':a.status}:a);
 const v={...V};
 v.achievements=A(V.achievements).filter(x=>(N(x.chapter)??0)<=c).map(x=>({...x,title:rewriteNames(x.title,names)}));
 v.combat_records=A(V.combat_records).filter(x=>(N(x.chapter)??0)<=c).map(x=>({...x,protagonist:safeName(x.protagonist_id,names),opponents:A(x.opponent_ids).map(id=>safeName(id,names)),location:safeName(x.location_id,names)}));
 v.resources={items:A(V.resources?.items).map(x=>resourceAt(x,c,names)).filter(x=>x.role_history.length||x.quantity_history.length||x.rarity||x.supply)};
 v.skills=A(V.skills).map(x=>({...x,name:safeName(x.skill_id,names)||x.name,holders:A(x.holders).filter(h=>interval(h,c)).map(h=>({...h,entity:safeName(h.entity_id,names)}))}));
 v.commitments=A(V.commitments).filter(x=>(N(x.created_chapter)??0)<=c).map(x=>{const q=commitAt(x,c);q.promisors=A(q.promisor_ids).map(id=>safeName(id,names));q.counterparties=A(q.counterparty_ids).map(id=>safeName(id,names));return q});
 v.favor_ledger=A(V.favor_ledger).filter(x=>(N(x.valid_from)??0)<=c).map(x=>{const r=relationById[x.relation_id];return {...x,debtor:safeName(x.debtor_id,names),creditor:safeName(x.creditor_id,names),status:r?.status??x.status,valid_to:r?.valid_to}});
 v.knowledge={secrets:A(V.knowledge?.secrets).map(s=>({...s,secret:safeName(s.secret_id,names),people:A(s.people).map(p=>({...p,entity:safeName(p.entity_id,names),history:A(p.history).filter(h=>(N(h.chapter)??0)<=c)})).filter(p=>p.history.length)})).filter(s=>s.people.length),propagation:A(V.knowledge?.propagation).filter(x=>(N(x.chapter)??0)<=c).map(x=>({...x,secret:safeName(x.secret_id,names),from:safeName(x.from_id,names),to:safeName(x.to_id,names)}))};
 v.foreshadowing={rows:A(V.foreshadowing?.rows).filter(x=>(N(x.planted_chapter)??0)<=c).map(x=>N(x.payoff_chapter)!==null&&x.payoff_chapter>c?{...x,payoff_chapter:null,span:null,status:'open'}:x)};v.foreshadowing.unresolved=v.foreshadowing.rows.filter(x=>N(x.payoff_chapter)===null);
 v.levels={series:A(V.levels?.series).map(s=>({...s,entity:safeName(s.entity_id,names),facets:Object.fromEntries(Object.entries(s.facets||{}).map(([k,z])=>[k,A(z).filter(x=>(N(x.chapter)??0)<=c)]))})).filter(s=>Object.values(s.facets).some(z=>z.length))};
 v.chapter_rhythm={chapters:A(V.chapter_rhythm?.chapters).filter(x=>(N(x.chapter)??0)<=c).map(x=>({...x,pov:A(x.pov_entity_ids).map(id=>safeName(id,names))}))};
 v.romance={routes:A(V.romance?.routes).map(r=>({...r,character:safeName(r.character_id,names),milestones:A(r.milestones).filter(m=>(N(m.chapter)??0)<=c)})).filter(r=>r.milestones.length)};
 v.mortality={events:A(V.mortality?.events).filter(x=>(N(x.chapter)??0)<=c).map(x=>({...x,entity:safeName(x.entity_id,names),killers:A(x.killer_ids).map(id=>safeName(id,names))}))};
 v.economy={transactions:A(V.economy?.transactions).filter(x=>(N(x.chapter)??0)<=c),wealth_changes:A(V.economy?.wealth_changes).filter(x=>(N(x.chapter)??0)<=c)};
 v.rules={concepts:A(V.rules?.concepts).filter(x=>(N(x.first_chapter)??0)<=c).map(x=>{const e=entities.find(y=>y.id===x.id);return {...x,name:safeName(x.id,names),summary:e?.summary}}),enforcement_events:A(V.rules?.enforcement_events).filter(x=>(N(x.chapter)??0)<=c)};
 v.narrative={character_voice:A(V.narrative?.character_voice).map(x=>({...x,entity:safeName(x.entity_id,names),observations:A(x.observations).filter(o=>{const s=N(o.chapter)??N(o.chapter_start)??N(o.valid_from);return s!==null&&s<=c})})).filter(x=>x.observations.length),author_style:A(V.narrative?.author_style).filter(o=>{const s=N(o.chapter)??N(o.chapter_start)??N(o.valid_from);return s!==null&&s<=c})};
 const s={chapter:c,graph:{entities,relations,events},arcs,views:v,names,intimate_acts:A(G.intimate_acts).filter(x=>(N(x.chapter)??0)<=c),chapter_summaries:A(G.chapter_summaries).filter(x=>(N(x.chapter)??0)<=c),review_issues:A(G.review_issues).filter(x=>(N(x.chapter)??0)<=c)};s.collections=A(C.collections).map(x=>({id:x.id,label:x.label,members:[...expr(x.expression,s)]}));return s
}
const panels=[['overview','总览'],['graph','关系图'],['repo','仓库'],['arcs','剧情线'],['collections','集合'],['achievements','成就'],['combat','战绩'],['resources','资源'],['skills','技能'],['commitments','承诺'],['knowledge','秘密'],['foreshadowing','伏笔'],['levels','成长'],['rhythm','节奏'],['romance','感情 / 亲密'],['mortality','生死'],['economy','经济'],['rules','规则'],['narrative','写法'],['audit','审计']];
for(const [id,t] of panels){const b=document.createElement('button');b.textContent=t;b.dataset.panel=id;b.onclick=()=>{active=id;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('on',x===b));render()};if(id==='overview')b.className='on';tabsEl.appendChild(b)}
function set(x){mainEl.innerHTML=`<section>${x}</section>`}function empty(label='当前章节无数据'){return `<div class=empty>${E(label)}</div>`}function tag(t,c=''){return `<span class="tag ${c}">${E(t)}</span>`}function viewHead(title,desc,eyebrow=''){return `<div class=view-head><div>${eyebrow?`<div class=eyebrow>${E(eyebrow)}</div>`:''}<h2>${E(title)}</h2><p>${E(desc)}</p></div></div>`}function table(h,rows){if(!rows.length)return empty();return `<div class=scroll><table><thead><tr>${h.map(x=>`<th>${E(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x??''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderOverview(){const v=S.views,open=v.commitments.filter(x=>['active','partially_fulfilled','uncertain'].includes(x.status)),recent=S.graph.events.slice(-5).reverse(),activeArcs=S.arcs.filter(a=>!a.chapter_end||a.chapter_end>=S.chapter).slice(0,5),intimacy=S.intimate_acts.length;const metrics=[[S.graph.entities.length,'实体'],[S.graph.events.length,'事件'],[v.combat_records.filter(x=>x.result==='victory').length,'胜场'],[open.length,'未完承诺'],[v.foreshadowing.unresolved.length,'未收伏笔'],[intimacy,'亲密记录']];set(`<div class=hero><div class=hero-main><div class=eyebrow>当前阅读快照</div><h2>第 ${S.chapter} 章的世界状态</h2><p>人物、关系、成长、战斗、感情和伏笔全部来自同一个时序快照。移动上方章节滑块即可回到任意历史节点。</p><div class=chips style="margin-top:14px">${tag(`${S.graph.relations.length} 条活动关系`,'accent')}${tag(`${activeArcs.length} 条当前剧情线`)}${B.metadata?.cutoff!=null?tag(`分享截止 ${B.metadata.cutoff}`,'warn'):''}</div></div><div class=hero-side>${metrics.slice(0,4).map(x=>`<div class="card metric-card"><div class=metric>${x[0]}</div><div class=muted>${x[1]}</div></div>`).join('')}</div></div><div class=grid>${metrics.slice(4).map(x=>`<div class="card metric-card"><div class=metric>${x[0]}</div><div class=muted>${x[1]}</div></div>`).join('')}</div><div class=grid style="margin-top:14px"><div class=card><div class=eyebrow>最近事件</div>${recent.length?recent.map(x=>`<div style="padding:9px 0;border-bottom:1px solid var(--line)"><b>第${x.chapter}章 · ${E(x.title||x.type||x.id)}</b><div class=muted>${E(x.description||'')}</div></div>`).join(''):empty()}</div><div class=card><div class=eyebrow>当前剧情线</div>${activeArcs.length?activeArcs.map(a=>`<div style="padding:9px 0;border-bottom:1px solid var(--line)"><b>${E(a.title||a.id)}</b><div class=muted>第 ${a.chapter_start} 章起 · ${E(a.status||'进行中')}</div></div>`).join(''):empty()}</div></div>`)}
function renderGraph(){set(`${viewHead('人物与世界关系图','点击节点查看实体详情；当前只显示所选章节已经成立的关系。','关系网络')}<div class=graph-shell><div class=graph-toolbar><button id=nkgFitGraph>适应画布</button><button id=nkgRelayout>重新布局</button></div><div id=cy class=graph></div></div><div class=graph-legend>${Object.entries(TYPE_LABELS).map(([k,v])=>`<span class=legend-item><span class=swatch style="background:${TYPE_COLORS[k]||'#758097'}"></span>${E(v)}</span>`).join('')}</div>`);const ns=S.graph.entities.slice(0,180).map(e=>({data:{id:e.id,label:e.name,type:e.type}})),keep=new Set(ns.map(x=>x.data.id)),es=S.graph.relations.filter(r=>keep.has(r.source_id)&&keep.has(r.target_id)).slice(0,320).map(r=>({data:{id:r.id,source:r.source_id,target:r.target_id,label:REL_LABELS[r.relation_type]||r.relation_type}}));if(cy)cy.destroy();if(typeof cytoscape!=='undefined'){cy=cytoscape({container:document.getElementById('cy'),elements:[...ns,...es],minZoom:.25,maxZoom:3.5,pixelRatio:Math.max(1,Math.min(3,window.devicePixelRatio||1)),style:[{selector:'node',style:{label:'data(label)','font-family':'Inter, Segoe UI, Microsoft YaHei, sans-serif','font-size':11,'font-weight':600,'background-color':e=>TYPE_COLORS[e.data('type')]||'#758097','width':e=>e.data('type')==='character'?34:26,'height':e=>e.data('type')==='character'?34:26,'color':'#2b3040','text-background-color':'#fff','text-background-opacity':.92,'text-background-padding':3,'text-background-shape':'roundrectangle','text-margin-y':8,'text-valign':'bottom','border-width':2,'border-color':'#fff','overlay-opacity':0}},{selector:'node[type="skill"]',style:{shape:'round-rectangle'}},{selector:'node[type="item"]',style:{shape:'diamond'}},{selector:'node[type="martial_soul"]',style:{shape:'hexagon'}},{selector:'node[type="organization"]',style:{shape:'rectangle'}},{selector:'node[type="location"]',style:{shape:'tag'}},{selector:'edge',style:{width:1.4,'line-color':'#b9bfca','target-arrow-color':'#b9bfca','target-arrow-shape':'triangle','arrow-scale':.7,'curve-style':'bezier','opacity':.58,'overlay-opacity':0}},{selector:'edge:selected',style:{'line-color':'#6157d8','target-arrow-color':'#6157d8','width':3,'opacity':1,'label':'data(label)','font-size':10,'color':'#5148bd','text-background-color':'#fff','text-background-opacity':1,'text-background-padding':3}},{selector:'node:selected',style:{'border-color':'#262143','border-width':4,'width':42,'height':42}}],layout:{name:'cose',animate:false,fit:true,padding:55}});document.getElementById('nkgFitGraph').onclick=()=>cy.fit(undefined,55);document.getElementById('nkgRelayout').onclick=()=>cy.layout({name:'cose',animate:false,fit:true,padding:55}).run()}}
function renderRepo(){const q=repoQuery.trim().toLowerCase(),rows=S.graph.entities.filter(e=>!q||[e.name,e.type,e.summary,...Object.values(e.attributes||{})].join(' ').toLowerCase().includes(q));set(`${viewHead('实体仓库','人物、物品、技能、组织和地点统一收录；点击卡片查看历史与证据。','实体索引')}<div class=searchbar><input id=nkgRepoSearch type=search value="${E(repoQuery)}" placeholder="搜索名称、类型、摘要或属性"><span class=tag>${rows.length} / ${S.graph.entities.length}</span></div>${rows.length?`<div class=entity-grid>${rows.slice(0,240).map(e=>`<button class="entity-card nkgEntityCard" data-entity-id="${E(e.id)}" style="border-top:3px solid ${TYPE_COLORS[e.type]||'#758097'}"><div class=record-head>${tag(TYPE_LABELS[e.type]||e.type)}<span class=muted>首次 · 第${e.first_chapter??'?'}章</span></div><h3>${E(e.name)}</h3><p>${E(e.summary||e.description||'暂无摘要')}</p><div class=entity-attrs>${Object.entries(e.attributes||{}).slice(0,3).map(([k,v])=>tag(`${k} · ${typeof v==='object'?JSON.stringify(v):v}`)).join('')}</div></button>`).join('')}</div>`:empty('没有匹配的实体')}`);const search=document.getElementById('nkgRepoSearch');search.oninput=e=>{repoQuery=e.target.value;renderRepo()}}
function renderArcs(){const span=Math.max(1,max-min+1);set(`${viewHead('剧情线','用一条连续时间带查看主线、子线和并行剧情在当前章节之前如何展开。','Story arcs')}${S.arcs.length?`<div class=arc-list>${S.arcs.map(a=>{const start=Math.max(min,N(a.chapter_start)??min),end=Math.min(S.chapter,N(a.chapter_end)??S.chapter),left=((start-min)/span)*100,width=Math.max(1,((end-start+1)/span)*100);return `<div class=arc-card><div class=arc-head><h3>${E(a.title||a.id)}</h3><div>${tag(a.status||'active',a.status==='resolved'?'good':'accent')}</div></div><div class=arc-range>第 ${start} 章 → ${a.chapter_end??'当前'} ${a.phase?` · ${E(a.phase)}`:''}</div><div class=arc-track><div class=arc-bar style="left:${left}%;width:${width}%"></div></div><div class=arc-sub>${A(a.entity_ids).slice(0,8).map(id=>E(S.names[id]||id)).join(' · ')}</div></div>`}).join('')}</div>`:empty()}`)}
function renderCollections(){set(`${viewHead('集合','保存的多成员视图，适合势力、路线和自定义交集。','Collections')}${S.collections.length?`<div class=record-grid>${S.collections.map(c=>`<div class=record-card><div class=record-head><h3>${E(c.label||c.id)}</h3><span class=record-value>${c.members.length}</span></div><div class=chips>${c.members.slice(0,14).map(id=>tag(S.names[id]||id)).join('')}</div></div>`).join('')}</div>`:empty()}`)}
function renderAchievements(){const rows=[...S.views.achievements].sort((a,b)=>(N(b.chapter)??0)-(N(a.chapter)??0));set(`${viewHead('成就与关键成果','按时间阅读角色已经完成的重要突破、成果与里程碑。','Achievements')}${rows.length?`<div class=timeline>${rows.slice(0,160).map(x=>`<div class=timeline-item><div class=timeline-chapter>第${x.chapter}章</div><div class=timeline-rail><span class=timeline-dot></span></div><div class=timeline-body><div class=chips>${tag(x.category||'成就','accent')}</div><h3>${E(x.title)}</h3></div></div>`).join('')}</div>`:empty()}`)}
function renderCombat(){const rows=S.views.combat_records,wins=rows.filter(x=>x.result==='victory').length,losses=rows.filter(x=>['defeat','loss'].includes(x.result)).length;set(`${viewHead('战斗记录','每场战斗独立呈现对手、结果和当时境界，而不是只给一张总表。','Combat')}<div class=grid style="margin-bottom:14px"><div class="card metric-card"><div class=metric>${rows.length}</div><div class=muted>记录战斗</div></div><div class="card metric-card"><div class=metric>${wins}</div><div class=muted>胜场</div></div><div class="card metric-card"><div class=metric>${losses}</div><div class=muted>败场</div></div></div>${rows.length?`<div class=record-grid>${[...rows].reverse().map(x=>`<div class="record-card battle-card ${E(x.result||'')}"><div class=record-head>${tag(`第${x.chapter}章`)}${tag(x.result||'未知',x.result==='victory'?'good':(['defeat','loss'].includes(x.result)?'danger':'warn'))}</div><h3>${E(x.protagonist||'主角')} vs ${E(A(x.opponents).join('、')||'未知对手')}</h3><p>${x.location?`地点 · ${E(x.location)}`:''}</p>${x.protagonist_level?`<div class=chips style="margin-top:9px">${Object.entries(x.protagonist_level).map(([k,v])=>tag(`${k} · ${typeof v==='object'?JSON.stringify(v):v}`,'accent')).join('')}</div>`:''}</div>`).join('')}</div>`:empty()}`)}
function renderResources(){const rows=S.views.resources.items;set(`${viewHead('物品与资源','当前持有、获得历史、稀有度和数量状态。','Resources')}${rows.length?`<div class=record-grid>${rows.map(x=>`<div class=record-card><div class=record-head><h3>${E(x.name)}</h3>${x.rarity?tag(x.rarity,'accent'):''}</div><p>累计获得 ${x.acquisition_count||0} 次</p><div class=chips style="margin-top:9px">${Object.entries(x.current_quantities||{}).slice(0,8).map(([id,v])=>tag(`${S.names[id]||id} · ${v}`)).join('')}</div></div>`).join('')}</div>`:empty()}`)}
function renderSkills(){const rows=S.views.skills;set(`${viewHead('技能与能力','按技能本身查看分类和当前掌握者。','Abilities')}${rows.length?`<div class=record-grid>${rows.map(x=>`<div class=record-card><div class=record-head><h3>${E(x.name)}</h3>${tag(A(x.categories).join(' / ')||'未分类','accent')}</div><p>${A(x.holders).length?'当前掌握 · '+E(A(x.holders).map(h=>h.entity).join('、')):'当前章节无已知掌握者'}</p></div>`).join('')}</div>`:empty()}`)}
function renderCommitments(){const rows=S.views.commitments;set(`${viewHead('承诺、誓言与人情','仍在进行、已兑现或已经失效的承诺按状态展示。','Commitments')}${rows.length?`<div class=record-grid>${rows.map(x=>`<div class=record-card><div class=record-head>${tag(`第${x.created_chapter}章`)}${tag(x.status||'active',x.resolved_chapter?'good':'accent')}</div><h3>${E(x.terms)}</h3><p>${A(x.promisors).join('、')?`承诺者 · ${E(A(x.promisors).join('、'))}`:''}${A(x.counterparties).join('、')?` · 对象 · ${E(A(x.counterparties).join('、'))}`:''}</p>${x.resolved_chapter?`<div class=muted style="margin-top:8px">第 ${x.resolved_chapter} 章解决</div>`:''}</div>`).join('')}</div>`:empty()}`)}
function renderKnowledge(){const rows=S.views.knowledge.secrets;set(`${viewHead('秘密与知情传播','一个秘密由谁知道、何时知道，保持与关系网络分离。','Knowledge')}${rows.length?`<div class=record-grid>${rows.map(s=>`<div class=record-card><h3>${E(s.secret)}</h3><div class=chips>${A(s.people).map(p=>tag(`${p.entity} · ${p.history.length}次变化`)).join('')}</div></div>`).join('')}</div>`:empty()}`)}
function renderForeshadowing(){const rows=S.views.foreshadowing.rows;set(`${viewHead('伏笔与回收','把埋设与后续推进/回收放在同一条视觉链路上。','Foreshadowing')}${rows.length?`<div class=timeline>${rows.map(x=>`<div class=record-card foreshadow-card><div class=foreshadow-node><b>${E(x.label)}</b><span>埋设 · 第 ${x.planted_chapter} 章</span></div><div class=foreshadow-arrow>→</div><div class=foreshadow-node><b>${x.payoff_chapter?`第 ${x.payoff_chapter} 章回收`:'尚未回收'}</b><span>${E(x.status||'open')}</span></div></div>`).join('')}</div>`:empty()}`)}
function renderLevels(){const groups=[];for(const s of S.views.levels.series)for(const [k,h] of Object.entries(s.facets||{})){const hist=A(h);if(hist.length)groups.push([s,k,hist])}set(`${viewHead('成长与等级','每个人物的每一条等级轴都保留历史节点，当前值只高亮最后一步。','Progression')}${groups.length?`<div class=record-grid>${groups.map(([s,k,h])=>`<div class=level-group><h3>${E(s.entity)} · ${E(k)}</h3><div class=level-ladder>${h.slice(-14).map((z,i)=>`<span class="level-step ${i===h.slice(-14).length-1?'current':''}">第${z.chapter}章 · ${E(typeof z.after==='object'?JSON.stringify(z.after):z.after)}</span>`).join('')}</div></div>`).join('')}</div>`:empty()}`)}
function renderRhythm(){const rows=S.views.chapter_rhythm.chapters.slice(-120),peak=Math.max(1,...rows.map(x=>Number(x.event_total)||0));set(`${viewHead('章节节奏','事件密度随章节变化；高柱表示该章记录了更多结构化事件。','Chapter rhythm')}${rows.length?`<div class=rhythm-chart>${rows.map(x=>`<div class=rhythm-bar style="height:${Math.max(4,Math.round(((Number(x.event_total)||0)/peak)*160))}px"><span>第${x.chapter}章 · ${x.event_total||0}事件${x.cliffhanger_type?` · ${E(x.cliffhanger_type)}`:''}</span></div>`).join('')}</div>`:empty()}`)}
function namesForAct(x){const ids=[...A(x.initiator_ids),...A(x.recipient_ids),...A(x.observer_ids)];return [...new Set(ids)].map(id=>S.names[id]||id)}
function renderRomance(){const routes=S.views.romance.routes,acts=S.intimate_acts;set(`${viewHead('感情与亲密关系','感情路线和具体亲密行为分开记录：发生亲密行为不自动等于恋爱，恋爱也不自动等于发生亲密行为。','Romance & intimacy')}<div class=grid style="margin-bottom:14px"><div class="card metric-card"><div class=metric>${routes.length}</div><div class=muted>感情路线</div></div><div class="card metric-card"><div class=metric>${acts.length}</div><div class=muted>亲密行为记录</div></div></div><div class=view-head><div><h2 style="font-size:17px">感情路线</h2><p>按对象汇总路线状态与关键里程碑。</p></div></div>${routes.length?`<div class=record-grid>${routes.map(x=>`<div class="record-card romance-route"><div class=record-head><h3>${E(x.character)}</h3>${tag(x.status||'route','accent')}</div><div class=timeline style="margin-top:10px">${A(x.milestones).slice(-8).map(m=>`<div style="display:grid;grid-template-columns:68px 1fr;gap:8px"><b style="color:var(--accent)">第${m.chapter}章</b><span class=muted>${E(m.kind)}</span></div>`).join('')}</div></div>`).join('')}</div>`:empty('当前章节还没有感情路线里程碑')}<div class=view-head style="margin-top:24px"><div><h2 style="font-size:17px">亲密行为</h2><p>具体行为、参与者与同意语境独立呈现。</p></div></div>${acts.length?`<div class=record-grid>${[...acts].reverse().map(x=>`<div class="record-card intimacy-card"><div class=record-head>${tag(`第${x.chapter}章`)}${tag(ACT_LABELS[x.act_type]||x.act_type||'亲密行为','accent')}</div><h3>${E(namesForAct(x).join(' · ')||'参与者未标注')}</h3><p>${E(x.description||'')}</p><div class=chips style="margin-top:9px">${x.consent?tag(`同意语境 · ${x.consent}`,['coerced','forced'].includes(x.consent)?'danger':(x.consent==='mutual'?'good':'warn')):''}${x.nudity===true?tag('涉及裸露'):''}${x.ejaculation_site?tag(`射精位置 · ${x.ejaculation_site}`):''}</div></div>`).join('')}</div>`:empty('当前章节还没有亲密行为记录')}`)}
function renderMortality(){const rows=[...S.views.mortality.events].reverse();set(`${viewHead('生死与继承','死亡、复活和相关因果按章节回放。','Mortality')}${rows.length?`<div class=timeline>${rows.map(x=>`<div class=timeline-item><div class=timeline-chapter>第${x.chapter}章</div><div class=timeline-rail><span class=timeline-dot></span></div><div class=timeline-body><h3>${E(x.entity)}</h3><p>${E(x.cause||'未记录死因')}</p></div></div>`).join('')}</div>`:empty()}`)}
function renderEconomy(){const rows=S.views.economy.transactions;set(`${viewHead('经济与交易','交易、价格和财富变化保持为结构化事件。','Economy')}${rows.length?`<div class=record-grid>${[...rows].reverse().map(x=>`<div class=record-card><div class=record-head>${tag(`第${x.chapter}章`)}${x.amount!=null?`<span class=record-value>${E(x.amount)}</span>`:''}</div><h3>${E(x.title||x.event_id||'交易')}</h3></div>`).join('')}</div>`:empty()}`)}
function renderRules(){const rows=S.views.rules.concepts;set(`${viewHead('世界规则','概念、规则与其在文本中的执行记录。','Rules')}${rows.length?`<div class=record-grid>${rows.map(x=>`<div class=record-card><div class=chips>${A(x.categories).map(c=>tag(c)).join('')}</div><h3>${E(x.name)}</h3><p>${E(x.summary||'')}</p></div>`).join('')}</div>`:empty()}`)}
function renderNarrative(){const rows=[];for(const x of S.views.narrative.character_voice)for(const o of A(x.observations))rows.push([x,o]);set(`${viewHead('人物声音与叙事写法','把角色说话风格和作者写法观察当作派生阅读辅助，而不是故事事实。','Narrative')}${rows.length?`<div class=record-grid>${rows.slice(-180).reverse().map(([x,o])=>`<div class=record-card><div class=record-head><h3>${E(x.entity)}</h3>${tag(`第${N(o.chapter)??N(o.chapter_start)??'?'}章`)}</div><p>${E(o.observation||o.summary||o.text||'')}</p></div>`).join('')}</div>`:empty()}`)}
function renderAudit(){const gaps=A(B.metadata?.temporal_provenance_gaps),errors=V.contract_summary?.error_count??0,warnings=V.contract_summary?.warning_count??0;set(`${viewHead('构建质量与审计','质量指标用于发现证据、时序和完整度风险，不是“事实为真概率”。','Audit')}<div class=audit-grid><div class="card ${errors?'audit-error':'audit-good'}"><div class=metric>${errors}</div><div class=muted>契约错误</div></div><div class="card ${warnings?'audit-warn':'audit-good'}"><div class=metric>${warnings}</div><div class=muted>契约警告</div></div><div class="card ${gaps.length?'audit-warn':'audit-good'}"><div class=metric>${gaps.length}</div><div class=muted>无时间来源字段</div></div><div class="card ${S.review_issues.length?'audit-warn':'audit-good'}"><div class=metric>${S.review_issues.length}</div><div class=muted>当前可见待核项</div></div></div>`)}
function render(){if(active==='overview')return renderOverview();if(active==='graph')return renderGraph();if(active==='repo')return renderRepo();if(active==='arcs')return renderArcs();if(active==='collections')return renderCollections();if(active==='achievements')return renderAchievements();if(active==='combat')return renderCombat();if(active==='resources')return renderResources();if(active==='skills')return renderSkills();if(active==='commitments')return renderCommitments();if(active==='knowledge')return renderKnowledge();if(active==='foreshadowing')return renderForeshadowing();if(active==='levels')return renderLevels();if(active==='rhythm')return renderRhythm();if(active==='romance')return renderRomance();if(active==='mortality')return renderMortality();if(active==='economy')return renderEconomy();if(active==='rules')return renderRules();if(active==='narrative')return renderNarrative();return renderAudit()}
function refresh(){const c=Number(sl.value);document.getElementById('cl').textContent=c;S=snapshotAt(c);document.getElementById('state').textContent=`${S.graph.entities.length} 实体 · ${S.graph.events.length} 事件${B.metadata?.cutoff!=null?' · cutoff '+B.metadata.cutoff:''}`;render()}sl.addEventListener('input',refresh);refresh();
</script>
</body></html>'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--graph", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--collection-manifest", type=Path)
    parser.add_argument("--cutoff", type=int)
    parser.add_argument("--protagonist-id", action="append", default=[])
    parser.add_argument("--relation-gap-threshold", type=int, default=3)
    args = parser.parse_args()
    graph = json.loads(args.graph.read_text(encoding="utf-8"))
    collections = json.loads(args.collection_manifest.read_text(encoding="utf-8")) if args.collection_manifest else None
    model = build_model(graph, args.protagonist_id, args.relation_gap_threshold, collections, args.cutoff)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    out = args.output_dir / "dashboard.html"
    atomic_write_text(out, build_html(model))
    asset = Path(__file__).resolve().parent.parent / "assets" / "cytoscape-3.34.3.min.js"
    if asset.exists():
        shutil.copy2(asset, args.output_dir / asset.name)
    print(json.dumps({"dashboard": str(out), "cutoff": args.cutoff, "unified": True}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
