#!/usr/bin/env python3
"""Build one dashboard for legacy graph views and expansion views.

The browser has exactly one chapter state. ``snapshotAt(chapter)`` is evaluated
once on slider movement and every panel renders from that shared snapshot.
"""
from __future__ import annotations
import argparse, html, json, shutil
from pathlib import Path
from typing import Any
from derive_novel_views import build_views
from filter_graph_asof import filter_graph


def build_model(graph:dict[str,Any], protagonists=(), gap_threshold:int=3, collections:dict[str,Any]|None=None, cutoff:int|None=None)->dict[str,Any]:
    scoped=filter_graph(graph,cutoff,strict=True) if cutoff is not None else graph
    meta=scoped.get("metadata") if isinstance(scoped.get("metadata"),dict) else {}
    return {"graph":scoped,"views":build_views(scoped,protagonists,max(1,gap_threshold)),"collections":collections or {"collections":[]},"metadata":{"title":meta.get("title"),"chapter_start":meta.get("chapter_start"),"chapter_end":meta.get("chapter_end"),"cutoff":cutoff,"temporal_provenance_gaps":meta.get("temporal_provenance_gaps",[])}}


def build_html(model:dict[str,Any])->str:
    payload=json.dumps(model,ensure_ascii=False,separators=(",",":")).replace("</","<\\/")
    title=html.escape(str(model.get("metadata",{}).get("title") or "Novel Knowledge Graph"))
    return TEMPLATE.replace("__PAYLOAD__",payload).replace("__TITLE__",title)

TEMPLATE=r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__ · Dashboard</title><style>
:root{--b:#0d1117;--p:#161b22;--l:#30363d;--t:#e6edf3;--m:#8b949e;--a:#58a6ff}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--t);font:13px system-ui}header{position:sticky;top:0;z-index:3;background:#0d1117f5;padding:12px 16px;border-bottom:1px solid var(--l)}h1{font-size:19px;margin:0 0 8px}.bar{display:flex;gap:10px;align-items:center}input{flex:1}nav{display:flex;gap:6px;overflow:auto;padding:7px 10px;background:var(--p);position:sticky;top:72px;z-index:2}button{background:#21262d;color:var(--t);border:1px solid var(--l);border-radius:7px;padding:6px 8px;white-space:nowrap}button.on{border-color:var(--a)}main{padding:14px;max-width:1700px;margin:auto}.panel{display:none}.panel.on{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:8px}.card{background:var(--p);border:1px solid var(--l);border-radius:9px;padding:9px}.metric{font-size:24px;font-weight:700}.muted{color:var(--m)}.scroll{overflow:auto;max-height:72vh;border:1px solid var(--l);border-radius:8px}table{width:100%;border-collapse:collapse;background:var(--p)}th,td{padding:7px;border-bottom:1px solid var(--l);vertical-align:top;text-align:left}th{position:sticky;top:0;background:#21262d}.graph{height:60vh;min-height:420px;border:1px solid var(--l);border-radius:9px}code{white-space:pre-wrap;font-size:11px}.warn{color:#f2cc60}
</style><script src="cytoscape-3.34.3.min.js"></script></head><body><header><h1>__TITLE__ · 统一时序 Dashboard</h1><div class="bar"><b>章节 <span id="cl"></span></b><input id="ch" type="range" step="1"><span id="state" class="muted"></span></div></header><nav id="tabs"></nav><main id="main"></main><script>
const B=__PAYLOAD__,G=B.graph||{},V=B.views||{},C=B.collections||{collections:[]};const A=x=>Array.isArray(x)?x:[],N=x=>Number.isInteger(x)?x:null,E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const min=Number(B.metadata?.chapter_start??V.metadata?.chapter_start??0),max=Number(B.metadata?.chapter_end??V.metadata?.chapter_end??0),sl=document.getElementById('ch');sl.min=min;sl.max=max;sl.value=max;let S=null,active='overview',cy=null;
function interval(r,c,a='valid_from',z='valid_to'){let s=N(r[a])??0,e=N(r[z]);return s<=c&&(e===null||c<=e)}function nameAt(e,c){let h=A(e.name_history).filter(x=>(N(x.valid_from)??N(x.chapter)??1e15)<=c);h.sort((a,b)=>(N(a.valid_from)??N(a.chapter)??0)-(N(b.valid_from)??N(b.chapter)??0));return h.length?(h.at(-1).name??h.at(-1).value??e.name):((N(e.name_first_chapter)!==null&&e.name_first_chapter>c)?`[${e.type}:${e.id}]`:e.name)}
function commitAt(x,c){x=structuredClone(x);x.observations=A(x.observations).filter(o=>(N(o.chapter)??0)<=c);if(N(x.resolved_chapter)!==null&&x.resolved_chapter>c){x.resolved_chapter=null;x.resolution=null}let s=[...x.observations].reverse().find(o=>o.status)?.status;if(s)x.status=s;else if(!x.resolved_chapter)x.status='active';return x}function resourceAt(x,c){x=structuredClone(x);x.role_history=A(x.role_history).filter(r=>(N(r.chapter)??0)<=c&&interval(r,c,'chapter','valid_to'));x.quantity_history=A(x.quantity_history).filter(r=>(N(r.chapter)??0)<=c);x.current_quantities={};for(const r of x.quantity_history)if(r.entity_id)x.current_quantities[r.entity_id]=r.after;x.acquisition_count=x.role_history.filter(r=>r.action==='gained').length;return x}
function expr(q,s,stack=[]){let all=new Set(s.graph.entities.map(e=>e.id));if(!q||typeof q!=='object')return new Set();if(q.explicit_members)return new Set(A(q.explicit_members).filter(x=>all.has(x)));if(q.type)return new Set(s.graph.entities.filter(e=>e.type===q.type).map(e=>e.id));if(q.arc){let a=s.arcs.find(x=>x.id===q.arc);return new Set(A(a?.entity_ids).filter(x=>all.has(x)))}if(q.collection){if(stack.includes(q.collection))return new Set();let c=A(C.collections).find(x=>x.id===q.collection);return c?expr(c.expression,s,[...stack,q.collection]):new Set()}if(q.and){let ss=A(q.and).map(x=>expr(x,s,stack));return ss.length?new Set([...ss[0]].filter(x=>ss.slice(1).every(z=>z.has(x)))):new Set()}if(q.or){let o=new Set();for(const z of A(q.or).map(x=>expr(x,s,stack)))for(const x of z)o.add(x);return o}if(q.not){let bad=expr(q.not,s,stack);return new Set([...all].filter(x=>!bad.has(x)))}if(q.relation){let spec=typeof q.relation==='string'?{type:q.relation}:q.relation,o=new Set();for(const r of s.graph.relations){if((spec.type||spec.relation_type)&&r.relation_type!==(spec.type||spec.relation_type))continue;o.add(r.source_id);o.add(r.target_id)}return new Set([...o].filter(x=>all.has(x)))}return new Set()}
function snapshotAt(c){let entities=A(G.entities).filter(e=>(N(e.first_chapter)??0)<=c).map(e=>({...e,name:nameAt(e,c)})),ids=new Set(entities.map(e=>e.id)),rh=A(G.relations).filter(r=>(N(r.valid_from)??0)<=c&&ids.has(r.source_id)&&ids.has(r.target_id)),relations=rh.filter(r=>interval(r,c)),events=A(G.events).filter(e=>(N(e.chapter)??0)<=c),arcs=A(G.story_arcs).filter(a=>(N(a.chapter_start)??0)<=c),names=Object.fromEntries(entities.map(e=>[e.id,e.name]));let v={...V};v.achievements=A(V.achievements).filter(x=>(N(x.chapter)??0)<=c);v.combat_records=A(V.combat_records).filter(x=>(N(x.chapter)??0)<=c);v.resources={items:A(V.resources?.items).map(x=>resourceAt(x,c)).filter(x=>x.role_history.length||x.quantity_history.length||x.rarity||x.supply)};v.skills=A(V.skills).map(x=>({...x,holders:A(x.holders).filter(h=>interval(h,c))}));v.commitments=A(V.commitments).filter(x=>(N(x.created_chapter)??0)<=c).map(x=>commitAt(x,c));v.favor_ledger=A(V.favor_ledger).filter(x=>(N(x.valid_from)??0)<=c);v.knowledge={secrets:A(V.knowledge?.secrets).map(s=>({...s,people:A(s.people).map(p=>({...p,history:A(p.history).filter(h=>(N(h.chapter)??0)<=c)})).filter(p=>p.history.length)})).filter(s=>s.people.length),propagation:A(V.knowledge?.propagation).filter(x=>(N(x.chapter)??0)<=c)};v.foreshadowing={rows:A(V.foreshadowing?.rows).filter(x=>(N(x.planted_chapter)??0)<=c).map(x=>N(x.payoff_chapter)!==null&&x.payoff_chapter>c?{...x,payoff_chapter:null,span:null,status:'active'}:x)};v.foreshadowing.unresolved=v.foreshadowing.rows.filter(x=>N(x.payoff_chapter)===null);v.levels={series:A(V.levels?.series).map(s=>({...s,facets:Object.fromEntries(Object.entries(s.facets||{}).map(([k,z])=>[k,A(z).filter(x=>(N(x.chapter)??0)<=c)]))})).filter(s=>Object.values(s.facets).some(z=>z.length))};v.chapter_rhythm={chapters:A(V.chapter_rhythm?.chapters).filter(x=>(N(x.chapter)??0)<=c)};v.romance={routes:A(V.romance?.routes).map(r=>({...r,milestones:A(r.milestones).filter(m=>(N(m.chapter)??0)<=c)})).filter(r=>r.milestones.length)};v.mortality={events:A(V.mortality?.events).filter(x=>(N(x.chapter)??0)<=c)};v.economy={transactions:A(V.economy?.transactions).filter(x=>(N(x.chapter)??0)<=c),wealth_changes:A(V.economy?.wealth_changes).filter(x=>(N(x.chapter)??0)<=c)};v.rules={concepts:A(V.rules?.concepts).filter(x=>(N(x.first_chapter)??0)<=c),enforcement_events:A(V.rules?.enforcement_events).filter(x=>(N(x.chapter)??0)<=c)};v.narrative={character_voice:A(V.narrative?.character_voice).map(x=>({...x,observations:A(x.observations).filter(o=>{let s=N(o.chapter)??N(o.chapter_start)??N(o.valid_from);return s!==null&&s<=c})})).filter(x=>x.observations.length),author_style:A(V.narrative?.author_style).filter(o=>{let s=N(o.chapter)??N(o.chapter_start)??N(o.valid_from);return s!==null&&s<=c})};let s={chapter:c,graph:{entities,relations,events},arcs,views:v,names};s.collections=A(C.collections).map(x=>({id:x.id,label:x.label,members:[...expr(x.expression,s)]}));return s}
const panels=[['overview','总览'],['graph','关系图'],['repo','仓库'],['arcs','剧情线'],['collections','集合'],['achievements','成就'],['combat','战绩'],['resources','资源'],['skills','技能'],['commitments','承诺'],['knowledge','秘密'],['foreshadowing','伏笔'],['levels','战力'],['rhythm','节奏'],['romance','感情'],['mortality','生死'],['economy','经济'],['rules','规则'],['narrative','写法'],['audit','审计']];for(const [id,t] of panels){let b=document.createElement('button');b.textContent=t;b.onclick=()=>{active=id;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('on',x===b));render()};if(id==='overview')b.className='on';tabs.appendChild(b)}
function table(h,rows){if(!rows.length)return '<div class="card muted">当前章节无数据</div>';return `<div class=scroll><table><thead><tr>${h.map(x=>`<th>${E(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x??''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}function set(x){main.innerHTML=`<section class="panel on">${x}</section>`}
function render(){
 const v=S.views;
 if(active==='overview'){
  const open=v.commitments.filter(x=>['active','partially_fulfilled','uncertain'].includes(x.status));
  const metrics=[[S.graph.entities.length,'实体'],[S.graph.events.length,'事件'],[v.achievements.length,'成就'],[v.combat_records.filter(x=>x.result==='victory').length,'胜场'],[open.length,'未完承诺'],[v.foreshadowing.unresolved.length,'未收伏笔']];
  const cards=metrics.map(x=>`<div class=card><div class=metric>${x[0]}</div><div class=muted>${x[1]}</div></div>`).join('');
  const gap=A(B.metadata?.temporal_provenance_gaps).length;
  set(`<div class=grid>${cards}</div>${gap?`<div class="card warn">严格防剧透隐藏 ${gap} 个无时间来源字段</div>`:''}`);return;
 }
 if(active==='graph'){
  set('<div id="cy" class=graph></div>');
  const ns=S.graph.entities.slice(0,100).map(e=>({data:{id:e.id,label:e.name}}));const keep=new Set(ns.map(x=>x.data.id));const es=S.graph.relations.filter(r=>keep.has(r.source_id)&&keep.has(r.target_id)).slice(0,180).map(r=>({data:{id:r.id,source:r.source_id,target:r.target_id,label:r.relation_type}}));
  if(cy)cy.destroy();if(typeof cytoscape!=='undefined')cy=cytoscape({container:document.getElementById('cy'),elements:[...ns,...es],style:[{selector:'node',style:{label:'data(label)','font-size':10,'background-color':'#58a6ff','color':'#fff'}},{selector:'edge',style:{'target-arrow-shape':'triangle','curve-style':'bezier','line-color':'#6e7681','target-arrow-color':'#6e7681'}}],layout:{name:'cose',animate:false}});return;
 }
 if(active==='repo'){set(table(['类型','名称','属性'],S.graph.entities.map(e=>[E(e.type),E(e.name),`<code>${E(JSON.stringify(e.attributes||{}))}</code>`])));return;}
 if(active==='arcs'){set(table(['剧情线','起始','结束','状态'],S.arcs.map(a=>[E(a.title||a.id),a.chapter_start,a.chapter_end??'',E(a.status||'')])));return;}
 if(active==='collections'){set(table(['集合','成员数','成员'],S.collections.map(c=>[E(c.label||c.id),c.members.length,E(c.members.map(id=>S.names[id]||id).join('、'))])));return;}
 if(active==='achievements'){set(table(['章','类别','成就'],v.achievements.map(x=>[x.chapter,E(x.category),E(x.title)])));return;}
 if(active==='combat'){set(table(['章','对手','结果','当时境界'],v.combat_records.map(x=>[x.chapter,E(A(x.opponents).join('、')),E(x.result),`<code>${E(JSON.stringify(x.protagonist_level||{}))}</code>`])));return;}
 if(active==='resources'){set(table(['资源','稀有度','获得次数','当前数量'],v.resources.items.map(x=>[E(x.name),E(x.rarity||''),x.acquisition_count,`<code>${E(JSON.stringify(x.current_quantities||{}))}</code>`])));return;}
 if(active==='skills'){set(table(['技能','分类','当前掌握'],v.skills.map(x=>[E(x.name),E(A(x.categories).join('、')),E(A(x.holders).map(h=>h.entity).join('、'))])));return;}
 if(active==='commitments'){set(table(['建立章','内容','状态','解决章'],v.commitments.map(x=>[x.created_chapter,E(x.terms),E(x.status),x.resolved_chapter??''])));return;}
 if(active==='knowledge'){const rows=[];for(const s of v.knowledge.secrets)for(const person of A(s.people))rows.push([E(s.secret),E(person.entity),person.history.length]);set(table(['秘密','人物','知情变化'],rows));return;}
 if(active==='foreshadowing'){set(table(['伏笔','埋设','回收','状态'],v.foreshadowing.rows.map(x=>[E(x.label),x.planted_chapter,x.payoff_chapter??'',E(x.status)])));return;}
 if(active==='levels'){const rows=[];for(const s of v.levels.series)for(const [k,h] of Object.entries(s.facets||{})){const z=A(h).at(-1);if(z)rows.push([E(s.entity),E(k),z.chapter,E(JSON.stringify(z.after))]);}set(table(['人物','轴','章','当前值'],rows));return;}
 if(active==='rhythm'){set(table(['章','事件','POV','断章'],v.chapter_rhythm.chapters.slice(-250).map(x=>[x.chapter,x.event_total,E(A(x.pov).join('、')),E(x.cliffhanger_type||'')])));return;}
 if(active==='romance'){const rows=[];for(const x of v.romance.routes)for(const m of A(x.milestones))rows.push([E(x.character),m.chapter,E(m.kind)]);set(table(['人物','章','里程碑'],rows));return;}
 if(active==='mortality'){set(table(['章','人物','死因'],v.mortality.events.map(x=>[x.chapter,E(x.entity),E(x.cause||'')])));return;}
 if(active==='economy'){set(table(['章','交易','金额'],v.economy.transactions.map(x=>[x.chapter,E(x.title||x.event_id),E(x.amount??'')])));return;}
 if(active==='rules'){set(table(['规则','分类','摘要'],v.rules.concepts.map(x=>[E(x.name),E(A(x.categories).join('、')),E(x.summary||'')])));return;}
 if(active==='narrative'){const rows=[];for(const x of v.narrative.character_voice)for(const o of A(x.observations))rows.push([E(x.entity),N(o.chapter)??N(o.chapter_start)??'',E(o.observation||o.summary||o.text||'')]);set(table(['人物','章','声音观察'],rows));return;}
 set(`<div class=card><b>契约：</b>${v.contract_summary?.valid?'通过':'存在问题'} · errors ${v.contract_summary?.error_count??0} · warnings ${v.contract_summary?.warning_count??0}</div>`);
}
function refresh(){let c=Number(sl.value);document.getElementById('cl').textContent=c;S=snapshotAt(c);document.getElementById('state').textContent=`统一快照 · ${S.graph.entities.length} 实体 · ${S.graph.events.length} 事件${B.metadata?.cutoff!=null?' · cutoff '+B.metadata.cutoff:''}`;render()}sl.addEventListener('input',refresh);refresh();
</script></body></html>'''


def main()->int:
    p=argparse.ArgumentParser(description=__doc__);p.add_argument("--graph",required=True,type=Path);p.add_argument("--output-dir",required=True,type=Path);p.add_argument("--collection-manifest",type=Path);p.add_argument("--cutoff",type=int);p.add_argument("--protagonist-id",action="append",default=[]);p.add_argument("--relation-gap-threshold",type=int,default=3);a=p.parse_args()
    g=json.loads(a.graph.read_text(encoding="utf-8"));c=json.loads(a.collection_manifest.read_text(encoding="utf-8")) if a.collection_manifest else None;m=build_model(g,a.protagonist_id,a.relation_gap_threshold,c,a.cutoff);a.output_dir.mkdir(parents=True,exist_ok=True);out=a.output_dir/"dashboard.html";out.write_text(build_html(m),encoding="utf-8");asset=Path(__file__).resolve().parent.parent/"assets"/"cytoscape-3.34.3.min.js";shutil.copy2(asset,a.output_dir/asset.name) if asset.exists() else None;print(json.dumps({"dashboard":str(out),"cutoff":a.cutoff,"unified":True},ensure_ascii=False));return 0
if __name__=="__main__":raise SystemExit(main())
