"""Install a deliberate break into the page the REAL gate reads, so the gate's own report is the
verdict. Use this to answer "can this gate actually fail?".

Why not write a standalone harness that reimplements the gate's loop? Because that is what this
project did first, and it validated the logic while being structurally unable to catch the defect
that was actually present. Measured: a four-claim standalone harness returned 12/12 green in the
same revision where the real gate's new assertion was tautological. **A reimplementation proves
the reimplementation is right.**

The verdict must come out of the gate's own report (`accept.json` / the `checks` list), because
that is the artifact a reader trusts. So: patch a COPY of `accept_atlas.py`, inject the break from
the driver, run the copy, and read the report.

Second trap, hit on the first attempt at this: an injected break that installs nothing reports
exactly like a gate that cannot fail. The first version wrapped the page's `applyRoute`; the run
came back ALL CHECKS PASS. Cause: the page registers `window.addEventListener("hashchange",
applyRoute)`, which captured the function reference at registration time, so reassigning the name
never reached the listener (the stale-reference class of defect). The fix is to register an
ADDITIONAL listener, after the page's own, so it runs after `applyRoute` has re-rendered — and to
record proof of installation in the report (`report["degradation"]`) so "the break did not
install" can never be mistaken for "the gate did not catch it".

Usage:
  degrade_install_atlas.py --accept <accept_atlas.py> --js degrade_break_example.js --out <patched.py>

`--js` holds a single JS expression that the page evaluates; it must return an object describing
what it installed (that object is written to `report["degradation"]`). It runs with the page's
globals in scope (`RT`, `window.__atlasRoute`, `document`, ...), which is why it is passed as a
file rather than as a command-line string. `degrade_break_example.js` is the worked example: it
registers a later `hashchange` listener that removes `#sec-tags` on non-character subject pages
and reprints one raw tag value on a character page — the two breaks that produced `missing=7` and
`raw_ascii_on_page=1` against gate 45.

Line endings: every file is read and written with `newline=""` and the embedded JS is normalised
to LF, because `read_text`/`write_text` translate newlines on Windows — the patched copy would
otherwise differ from its source in every single line, and "the only change is the injected
block" would stop being checkable (measured elsewhere in this project: a silent LF -> CRLF
conversion added 6,105 bytes to a file that was supposed to be a byte-identical copy). The
insertion is now asserted to be the only edit.

Then run the patched copy exactly as the gate runs, e.g.
  python <patched.py> runs/<run>/dashboard.html runs/<run>/_brk
and compare `checks` against the unbroken run. Each break should produce a DISTINCT expected
signal; a break that changes nothing in `checks` means the gate does not cover it.
"""
import argparse
import pathlib
import sys

DEFAULT_ANCHOR = '''        report["counts"] = pg.evaluate("""() => ({'''

TEMPLATE = '''        # --- DEGRADATION INJECTION (temporary, generated by degrade_install_atlas.py) ---
        # Registered AFTER the page's own `hashchange` listener, so it runs after `applyRoute`
        # has re-rendered. Wrapping `applyRoute` instead does nothing: the page's listener
        # captured the function reference at registration time (stale reference).
        installed = pg.evaluate("""{js}""")
        report["degradation"] = installed
        print(f"degradation injection: {{installed}}")
        # --- END DEGRADATION INJECTION ---
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--accept", required=True, help="the gate script to patch (a copy is written)")
    ap.add_argument("--js", required=True, help="file holding the JS the page should evaluate")
    ap.add_argument("--out", required=True, help="where to write the patched copy")
    ap.add_argument("--anchor", default=DEFAULT_ANCHOR,
                    help="insertion point; must occur exactly once (default: before report['counts'])")
    args = ap.parse_args()

    src = pathlib.Path(args.accept)
    # newline="" everywhere: on Windows the default translation would rewrite the copy's line
    # endings, so the copy would no longer be a byte-level copy of its source.
    text = src.read_text(encoding="utf-8", newline="")
    n = text.count(args.anchor)
    assert n == 1, f"anchor occurs {n} times in {src.name}; give a --anchor that is unique"

    js = pathlib.Path(args.js).read_text(encoding="utf-8", newline="").replace("\r\n", "\n").strip()
    assert '"""' not in js, "the JS may not contain a triple quote (it is embedded in a docstring)"

    block = TEMPLATE.format(js=js)
    patched = text.replace(args.anchor, block + args.anchor)
    # The insertion is the ONLY edit: same prefix, same suffix, delta exactly the block's length.
    assert patched.startswith(text[:text.index(args.anchor)]), "text before the anchor changed"
    assert len(patched) - len(text) == len(block), "something besides the block was inserted"
    assert patched.replace(block, "", 1) == text, "removing the block must restore the source"

    out = pathlib.Path(args.out)
    out.write_text(patched, encoding="utf-8", newline="")
    crlf = out.read_bytes().count(b"\r\n")
    src_crlf = src.read_bytes().count(b"\r\n")
    assert crlf == src_crlf, f"line endings changed: source {src_crlf} CRLF, copy {crlf} CRLF"
    print(f"wrote {out} ({len(patched)} chars, patched at a unique anchor, "
          f"{crlf} CRLF — same as the source)")
    print("run it, then compare its `checks` with the unbroken run's — each break needs its own "
          "distinct signal, and `report['degradation']` must show the break actually installed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
